'use client';
import { useState } from 'react';
type Tool = { name: string; description: string; category: string };
const tools: Tool[] = [
  { category: 'Account', name: 'user_info()', description: 'Read the private AI Context Pack.' }, { category: 'Account', name: 'hello(platform)', description: 'Confirm a connected AI client.' },
  { category: 'Solana', name: 'get_wallet_address()', description: 'Return the bound Solana wallet.' }, { category: 'Solana', name: 'get_solana_asset_balances()', description: 'Read token balances and USD values.' }, { category: 'Solana', name: 'list_solana_swap_tokens()', description: 'List allowlisted symbols, mints, and decimals.' }, { category: 'Solana', name: 'create_solana_swap(inputToken, outputToken, amount, slippageBps)', description: 'Create a Jupiter swap for wallet review.' }, { category: 'Solana', name: 'create_solana_token_transfer(token, recipient, amount)', description: 'Create an SPL-token transfer for wallet review.' },
  { category: 'Solana', name: 'create_solana_swap_by_mint(inputMint, outputMint, amount)', description: 'Create a Jupiter swap by mint; amount is an atomic integer.' },
  { category: 'Content', name: 'publish_page(slug, title, content, public)', description: 'Publish an account-owned Markdown page.' }, { category: 'Content', name: 'publish_html(html)', description: 'Publish a standalone HTML document and return its public URL.' }, { category: 'Content', name: 'list_pages()', description: 'List available pages.' }, { category: 'Content', name: 'get_page_content(id | title)', description: 'Read one page by ID or title.' },
];
export function DashboardTools() { const [selected, setSelected] = useState(() => new Set(tools.map(t => t.name))); const [status, setStatus] = useState(''); const categories = [...new Set(tools.map(t => t.category))]; function toggle(name: string) { setSelected(current => { const next = new Set(current); next.has(name) ? next.delete(name) : next.add(name); return next; }); } async function exportSelected() { const chosen = tools.filter(t => selected.has(t.name)); await navigator.clipboard.writeText(JSON.stringify({ tools: chosen }, null, 2)).catch(() => undefined); setStatus(`${chosen.length} tool definition(s) copied as JSON.`); } return <section className="tools"><header className="tools-head"><div><p className="eyebrow">MCP TOOL CATALOG</p><h2>Choose what to export.</h2><p className="tools-intro">Selections export a portable catalog; they do not change server-side authorization.</p></div><button type="button" onClick={() => void exportSelected()} disabled={!selected.size}>Export selected ({selected.size})</button></header>{categories.map(category => <section className="tool-group" key={category}><h3>{category}</h3><ol className="tool-list">{tools.filter(t => t.category === category).map(tool => <li key={tool.name}><label className="tool-card ui-interactive-card"><input type="checkbox" checked={selected.has(tool.name)} onChange={() => toggle(tool.name)} /><span className="tool-card-content"><code className="endpoint">{tool.name}</code><span>{tool.description}</span></span></label></li>)}</ol></section>)}{status && <p className="swap-status" role="status">{status}</p>}</section>; }
