'use client';
import { useState } from 'react';
type Tool = { name: string; description: string; category: string; package?: 'Base' | 'Jupiter' };
const tools: Tool[] = [
  { category: 'Account', name: 'user_info()', description: 'Read the private AI Context Pack.' }, { category: 'Account', name: 'hello(platform)', description: 'Confirm a connected AI client.' },
  { category: 'Solana', package: 'Base', name: 'get_wallet_address()', description: 'Return the bound Solana wallet.' }, { category: 'Solana', package: 'Base', name: 'get_solana_asset_balances()', description: 'Read token balances and USD values.' }, { category: 'Solana', package: 'Base', name: 'create_solana_sol_transfer(recipient, amount)', description: 'Create a native-SOL transfer for wallet review.' }, { category: 'Solana', package: 'Base', name: 'create_solana_token_transfer(token, recipient, amount)', description: 'Create an SPL-token transfer for wallet review.' }, { category: 'Solana', package: 'Base', name: 'get_solana_transaction_status(transactionId)', description: 'Read an account-owned pending transaction status.' },
  { category: 'Solana', package: 'Jupiter', name: 'list_solana_swap_tokens()', description: 'List currently quoteable symbols, mints, and decimals.' }, { category: 'Solana', package: 'Jupiter', name: 'quote_solana_swap(inputToken, outputToken, amount, slippageBps)', description: 'Get a read-only route and expected output before creating a swap.' }, { category: 'Solana', package: 'Jupiter', name: 'create_solana_swap(inputToken, outputToken, amount, slippageBps)', description: 'Create a Jupiter swap for wallet review.' }, { category: 'Solana', package: 'Jupiter', name: 'create_solana_swap_by_mint(inputMint, outputMint, amount)', description: 'Create a Jupiter swap by mint; amount is atomic.' },
  { category: 'Hylo', name: 'list_hylo_assets(category)', description: 'List live Hylo asset symbols and mints before an operation.' }, { category: 'Hylo', name: 'create_hylo_buy_asset(assetSymbol, inputMint, inputAmountAtomic, slippageBps)', description: 'Create an unsigned swap into a Hylo asset for wallet review.' }, { category: 'Hylo', name: 'create_hylo_sell_asset(assetSymbol, outputMint, assetAmountAtomic, slippageBps)', description: 'Create an unsigned swap out of a Hylo asset for wallet review.' }, { category: 'Hylo', name: 'get_hylo_operation_guide(operation)', description: 'Show the matching Hylo MCP operation.' },
  { category: 'Content', name: 'publish_page(slug, title, content, public)', description: 'Publish an account-owned Markdown page.' }, { category: 'Content', name: 'publish_html(html)', description: 'Publish a standalone HTML document and return its public URL.' }, { category: 'Content', name: 'list_pages()', description: 'List available pages.' }, { category: 'Content', name: 'get_page_content(id | title)', description: 'Read one page by ID or title.' },
];
export function DashboardTools() { const [selected, setSelected] = useState(() => new Set(tools.map(t => t.name))); const [status, setStatus] = useState(''); const categories = [...new Set(tools.map(t => t.category))]; const toggle = (name: string) => setSelected(current => { const next = new Set(current); next.has(name) ? next.delete(name) : next.add(name); return next; }); const list = (items: Tool[]) => <ol className="tool-list">{items.map(tool => <li key={tool.name}><label className="tool-card ui-interactive-card"><input type="checkbox" checked={selected.has(tool.name)} onChange={() => toggle(tool.name)} /><span className="tool-card-content"><code className="endpoint">{tool.name}</code><span>{tool.description}</span></span></label></li>)}</ol>; async function exportSelected() { const chosen = tools.filter(t => selected.has(t.name)); await navigator.clipboard.writeText(JSON.stringify({ tools: chosen }, null, 2)).catch(() => undefined); setStatus(`${chosen.length} tool definition(s) copied as JSON.`); } return <section className="tools"><header className="tools-head"><div><p className="eyebrow">MCP TOOL CATALOG</p><h2>Choose what to export.</h2><p className="tools-intro">Solana tools are grouped by independently maintained plugin package. Hylo tools focus on unsigned buy/sell operations that reuse wallet review.</p></div><button type="button" onClick={() => void exportSelected()} disabled={!selected.size}>Export selected ({selected.size})</button></header>{categories.map(category => <section className="tool-group" key={category}><h3>{category}</h3>{category === 'Solana' ? <div className="tool-package-grid">{(['Base', 'Jupiter'] as const).map(packageName => <section className="tool-package" key={packageName}><p className="eyebrow">SOLANA / {packageName.toUpperCase()}</p><h4>{packageName === 'Base' ? 'Wallet & signing review' : 'Pricing & routing'}</h4>{list(tools.filter(tool => tool.category === category && tool.package === packageName))}</section>)}</div> : list(tools.filter(tool => tool.category === category))}</section>)}{status && <p className="swap-status" role="status">{status}</p>}</section>; }
