import { z } from 'zod';
import { createSwapByMintForUser, createSwapForUser, quoteableSolanaSwapTokens } from '@/lib/solana-swap';
import type { McpPluginContext, McpToolServer } from '@/lib/mcp/plugins/types';

/** Jupiter-specific discovery and unsigned routing tools. */
export function registerSolanaJupiterPlugin(server: McpToolServer, context: McpPluginContext) {
  server.tool('list_solana_swap_tokens', 'List configured and account-whitelisted Solana tokens currently quoteable by Jupiter. Call this before creating a symbol-based swap.', { inputToken: z.string().min(1).max(20).default('USDC'), amount: z.string().regex(/^\d+(\.\d+)?$/).default('1') }, async ({ inputToken, amount }: { inputToken: string; amount: string }, extra: any) => {
    try { const user = await context.currentUser(extra.authInfo?.extra?.githubId); const tokens = await quoteableSolanaSwapTokens(user.id, inputToken, amount); return { content: [{ type: 'text', text: JSON.stringify({ cluster: 'mainnet-beta', validatedAt: new Date().toISOString(), inputToken, amount, tokens: tokens.map(({ symbol, name, mint, decimals }) => ({ symbol, name, mint, decimals })) }) }] }; } catch (error) { return { content: [{ type: 'text', text: error instanceof Error ? error.message : 'Could not validate Jupiter token routes.' }], isError: true }; }
  });
  server.registerTool('create_solana_swap', { title: 'Create Solana swap', description: 'Create a Jupiter-routed Solana swap as an unsigned transaction for the bound wallet. It never receives a private key and never broadcasts.', inputSchema: { inputToken: z.string().min(1).max(20), outputToken: z.string().min(1).max(20), amount: z.string().regex(/^\d+(\.\d+)?$/), slippageBps: z.number().int().min(1).max(1000).default(50) }, outputSchema: context.reviewOutputSchema, _meta: { 'openai/outputTemplate': context.reviewUiUri, 'ui/resourceUri': context.reviewUiUri } }, async (args: any, extra: any) => {
    try { const user = await context.currentUser(extra.authInfo?.extra?.githubId); const result = await createSwapForUser(user.id, args); const reviewUrl = `${context.appOrigin()}/account/wallet?swap=${result.transactionId}`; return { content: [{ type: 'text', text: `Unsigned ${result.summary.inputToken} → ${result.summary.outputToken} swap created. Open ${reviewUrl} to review and trigger signing; it expires at ${result.expiresAt}.` }], structuredContent: { ...result, reviewUrl, signingRequired: true, nextStep: 'Open reviewUrl to inspect this immutable signing summary and trigger your wallet’s review-and-sign flow.' }, _meta: { 'openai/outputTemplate': context.reviewUiUri } }; } catch (error) { return { content: [{ type: 'text', text: error instanceof Error ? error.message : 'Could not create swap transaction.' }], isError: true }; }
  });
  server.registerTool('create_solana_swap_by_mint', { title: 'Create Solana swap by mint', description: 'Create an unsigned Jupiter swap using arbitrary Solana mints. amount is an atomic integer, not a display decimal.', inputSchema: { inputMint: z.string().min(32).max(64), outputMint: z.string().min(32).max(64), amount: z.string().regex(/^\d+$/), slippageBps: z.number().int().min(1).max(1000).default(50) }, outputSchema: context.reviewOutputSchema, _meta: { 'openai/outputTemplate': context.reviewUiUri, 'ui/resourceUri': context.reviewUiUri } }, async (args: any, extra: any) => {
    try { const user = await context.currentUser(extra.authInfo?.extra?.githubId); const result = await createSwapByMintForUser(user.id, args); const reviewUrl = `${context.appOrigin()}/account/wallet?swap=${result.transactionId}`; return { content: [{ type: 'text', text: `Unsigned mint-to-mint swap created. Atomic input amount: ${args.amount}. Open ${reviewUrl} to review and sign.` }], structuredContent: { ...result, reviewUrl, signingRequired: true }, _meta: { 'openai/outputTemplate': context.reviewUiUri } }; } catch (error) { return { content: [{ type: 'text', text: error instanceof Error ? error.message : 'Could not create mint-based swap.' }], isError: true }; }
  });
}
